#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

CONFIGURATION=gpsdservice

start_service() {
  # Reading config
  config_load "${CONFIGURATION}"
  local ip
 
  config_get IP venus ip
  
	procd_open_instance
	procd_set_param command socat -u /dev/mhi_LOOPBACK udp4-datagram:$ip:5800
	
	procd_set_param respawn ${respawn_threshold:-60} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}
