#!/bin/sh /etc/rc.common.

USE_PROCD=1
START=99
STOP=01

CONFIGURATION=gpsdservice

start_service() {
  # Reading config
  config_load "${CONFIGURATION}"
  local IP
 
  config_get IP venus IP
  
	procd_open_instance
	procd_set_param command socat
	procd_append_param command -u /dev/mhi_LOOPBACK udp4-datagram:$IP # append command parameters
	procd_close_instance
}
